apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongoapp
  template:
    metadata:
      name: mongocon
      labels:
        app: mongoapp
    spec:
      containers:
        - name: myapp
          image: mongo
          ports:
            - containerPort: 27017
          env:  
          - name: MONGO_INITDB_ROOT_USERNAME
            value: devdb   
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: devdb     
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongoapp
  ports:
  - port: 80
    targetPort: 27017

