apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongoapp
  template:
    metadata:
      name: mongocon
      labels:
        app: mongoapp
    spec:
      containers:
        - name: mongocon
          image: mongo
          ports:
            - containerPort: 27017
          env:  
          - name: MONGO_INITDB_ROOT_USERNAME
            value: devdb   
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: devdb
          volumeMounts:
          - name: mongovol
            mountPath: /data/db 
      volumes: 
      - name: mongovol
        persistentVolumeClaim:
         claimName: mongopvc

        
---
apiVersion: v1
kind: Service
metadata:
  name: mongosvc
spec:
  selector:
    app: mongoapp
  ports:
  - port: 27017
    targetPort: 27017


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongopvc
spec:
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce



##https://aws.amazon.com/premiumsupport/knowledge-center/eks-persistent-storage/ 
# Create EBS CSI ROLE WITH PERMISSIONS AND ATTACH TO NODES 

# {
#   "Version": "2012-10-17",
#   "Statement": [
#     {
#       "Effect": "Allow",
#       "Action": [
#         "ec2:AttachVolume",
#         "ec2:CreateSnapshot",
#         "ec2:CreateTags",
#         "ec2:CreateVolume",
#         "ec2:DeleteSnapshot",
#         "ec2:DeleteTags",
#         "ec2:DeleteVolume",
#         "ec2:DescribeInstances",
#         "ec2:DescribeSnapshots",
#         "ec2:DescribeTags",
#         "ec2:DescribeVolumes",
#         "ec2:DetachVolume"
#       ],
#       "Resource": "*"
#     }
#   ]
# }