apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
spec:
  selector:
    matchLabels:
      app: springbootapp
  template:
    metadata:
      labels:
        app: springbootapp
    spec:
      imagePullSecrets:
      - name: dockercred
      containers: 
      - name: springbootcon
        image: jeaggrey/spring-boot-mongo:8
        # resources: 
        #   limits:
        #     memory: "64Mi"
        #     cpu: "100m"
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DB_HOSTNAME
          value: mongo
        - name: MONGO_DB_USERNAME
          value: devdb
        - name: MONGO_DB_PASSWORD
          value: devdb   

---
apiVersion: v1
kind: Service
metadata:
  name: springsvc
spec:
  selector:
    app: springbootapp
  ports:
  - port: 80
    targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sprining
  labels:
    name: springing
spec:
  ingressClassName: nginx
  rules:
  - host: spring.josephaggrey.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: springsvc
            port: 
              number: 80

